### ISSUE TITLE
Documentation/JSON

### ISSUE THREAD

**Issue by gonzalezger01** [pistacheio/pistache#176] opened 2017-12-19 01:21 UTC
Hi there, is there any where I could find some updated documentation? Also there are some problems with the documentation that exists calling things under namespace net, when they should be namespace pistache. 

Also could you guys include in that updated documentation the proper way to do JSON with pistache. Loving the software!!

**Comment by xoac** [comment] 2017-12-19 15:59
duplicate of #101

**Comment by sandakith** [comment] 2017-12-27 15:59
I created a pull request ca316d3 to update the example listed. Please review and apply. Thanks

**Closed** 2021-03-26 21:38 UTC
Labels: doc, duplicate
